### ISSUE TITLE
マシンの操作を実装

### ISSUE THREAD

**Issue by asuka1975** [asuka1975/Air-Riding-3D#10]
キャラクターが乗っているときのみ操作可能にする．

**Comment by ShimamotoRiku** [comment]
嶋本が担当します．

**Comment by ShimamotoRiku** [comment]
・基本的に自動で前進する
・左右キーで旋回（原作の滑ってる感じは再現するか？）
・スペースキー（仮）でブレーキ

・チャージ機能は後回し
・マシンから降りる機能は後回し
・飛行動作は後回し
